In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

sns.set()
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv('Datasets\Multiple linear regression.csv')
df.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [7]:
y = df['GPA']
x = df[['SAT' , 'Rand 1,2,3']] 

x.shape

(84, 2)

In [9]:
reg = LinearRegression()
reg.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
#Getting slope
slope = reg.coef_
print(slope)
#Getting intercept
reg.intercept_

[ 0.00165354 -0.00826982]


0.29603261264909486

In [13]:
#A function for adjusted R-squared
def adjusted_Rsq(score, n, p):
    return 1-(1-score)*(n-1)/(n-p-1)

adjusted_Rsq(reg.score(x,y),84,2)

0.3920313482513401

In [18]:
from sklearn.feature_selection import f_regression

reg = f_regression(x , y)
p_values = reg[1]

In [19]:
p_values.round(3)

array([0.   , 0.676])

In [21]:
#Doing feature scaling by standardizing our data
from sklearn.preprocessing import StandardScaler
stdscaler = StandardScaler()

In [25]:
stdscaler.fit(x) #returns an object with info about the mean and std

StandardScaler(copy=True, with_mean=True, with_std=True)

In [28]:
#Running scaler object to standardize data of x
x_new = stdscaler.transform(x)
x_new

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [34]:
reg1 = LinearRegression()
reg1.fit(x_new, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
reg1.coef_

array([ 0.17181389, -0.00703007])

In [36]:
reg1.intercept_

3.330238095238095

In [38]:

new_df = pd.DataFrame(data = [[1700,1],[1800,2]], columns = ['SAT' , 'Rand 1,2,3'])
new_df

SAT  Rand 1,2,3
0  1700           1
1  1800           2

In [40]:
new_std_df = stdscaler.transform(new_df)
new_std_df

array([[-1.39811928, -1.24637147],
       [-0.43571643, -0.07002087]])

In [41]:
#Predicting outputs
reg1.predict(new_std_df)

array([3.09878385, 3.25586821])

In [42]:
from sklearn.model_selection import train_test_split

In [45]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [46]:
b = np.arange(500, 600)

In [47]:
train_test_split(a)

[array([ 26,  14,  80,  23,  46,  88,  44,   4,  35,  49,  96,   5,  57,
         37,  12,   8,  93,  81,  61,  11,  10,  18,  45,  71,  29,  33,
         90,  69,  94,  27,  59,  63,  87,  36,  60,  47,  16,  84,  32,
         39,  43,  77,  48,  17,  68,  73,  58, 100,  62,   6,  75,   9,
         72,  79,  15,  51,   1,  91,  30,  28,  97,   3,  19,  42,  54,
          2,  67,  74,  31,  24,  99,  66,  70,  50,  83]),
 array([98, 25, 65, 21, 22,  7, 86, 64, 53, 52, 13, 41, 38, 85, 95, 78, 92,
        34, 56, 55, 20, 82, 40, 89, 76])]

In [52]:
train_a, test_a, train_b, test_b = train_test_split(a,b, test_size= 0.2)

In [53]:
train_a.shape , test_a.shape

((80,), (20,))